# -*- coding: utf-8 -*-
"""notmaind.ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HVdwW9mBLMG4-_Ryv8cGSSfrtgPiJoBp
"""

import React from "react";
import { motion } from "framer-motion";

// Components for different pages
const Navbar = () => (
  <nav className="w-full max-w-5xl flex justify-between items-center mb-10">
    <h1 className="text-3xl font-bold text-blue-700">NoteMind AI</h1>
    <div className="space-x-4">
      <button className="px-4 py-2 rounded-xl bg-blue-600 text-white hover:bg-blue-700 transition">Login</button>
      <button className="px-4 py-2 rounded-xl bg-gray-200 hover:bg-gray-300 transition">Sign Up</button>
    </div>
  </nav>
);

const Footer = () => (
  <footer className="mt-16 text-gray-500 text-sm">© 2025 NoteMind AI — Smart Learning Assistant</footer>
);

const HeroSection = () => (
  <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="text-center max-w-3xl mb-12">
    <h2 className="text-5xl font-bold text-gray-800 leading-tight mb-4">AI yang Bikin Kamu <span className="text-blue-600">Belajar Lebih Cepat</span></h2>
    <p className="text-gray-600 text-lg">Ringkas PDF, ekstrak poin penting, parafrase teks, sampai chat langsung dengan dokumen.</p>
  </motion.div>
);

const UploadSection = () => (
  <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.6 }} className="bg-white rounded-2xl shadow-xl p-8 border border-gray-200">
    <h3 className="text-2xl font-semibold mb-3">📂 Upload Dokumen</h3>
    <div className="border-2 border-dashed border-gray-300 rounded-xl p-8 text-center text-gray-500 cursor-pointer hover:bg-gray-50 transition">
      Klik atau drop file PDF di sini
    </div>
  </motion.div>
);

const FeatureSection = () => (
  <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.6 }} className="bg-white rounded-2xl shadow-xl p-8 border border-gray-200">
    <h3 className="text-2xl font-semibold mb-3">✨ Fitur Unggulan</h3>
    <ul className="space-y-3 text-gray-700 text-lg">
      <li>• Ringkasan AI yang pintar</li>
      <li>• Ekstraksi poin penting otomatis</li>
      <li>• Parafrase kalimat</li>
      <li>• Chat langsung dengan PDF</li>
      <li>• Dashboard analisis dokumen</li>
    </ul>
  </motion.div>
);

const OutputSection = () => (
  <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="w-full max-w-5xl bg-white rounded-2xl shadow-xl p-8 mt-10 border border-gray-200">
    <h3 className="text-2xl font-semibold mb-3">📄 Hasil AI</h3>
    <p className="text-gray-500 italic">Output akan tampil di sini...</p>
  </motion.div>
);

const AINotesGenerator = () => (
  <div className="max-w-5xl w-full mx-auto mb-10">
    <h2 className="text-3xl font-bold text-blue-700 mb-4">🧠 AI Notes Generator</h2>
    <p className="text-gray-600">Fitur ini memungkinkan pengguna membuat ringkasan otomatis dari dokumen PDF atau catatan panjang.</p>
  </div>
);

const MindAnalyzer = () => (
  <div className="max-w-5xl w-full mx-auto mb-10">
    <h2 className="text-3xl font-bold text-blue-700 mb-4">🧮 Mind Analyzer</h2>
    <p className="text-gray-600">Menganalisis pola belajar dan catatan pengguna untuk meningkatkan produktivitas belajar.</p>
  </div>
);

const DashboardInsights = () => (
  <div className="max-w-5xl w-full mx-auto mb-10">
    <h2 className="text-3xl font-bold text-blue-700 mb-4">📊 Dashboard Insights</h2>
    <p className="text-gray-600">Menampilkan statistik dokumen, jumlah ringkasan, poin penting, dan aktivitas pengguna.</p>
  </div>
);

const UserProfile = () => (
  <div className="max-w-5xl w-full mx-auto mb-10">
    <h2 className="text-3xl font-bold text-blue-700 mb-4">👤 User Profile</h2>
    <p className="text-gray-600">Halaman profil pengguna dengan pengaturan akun dan histori ringkasan.</p>
  </div>
);

const Pricing = () => (
  <div className="max-w-5xl w-full mx-auto mb-10">
    <h2 className="text-3xl font-bold text-blue-700 mb-4">💳 Pricing</h2>
    <p className="text-gray-600">Menawarkan paket gratis dan premium dengan fitur lebih lengkap untuk pengalaman belajar maksimal.</p>
  </div>
);

export default function App() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white flex flex-col items-center p-6 font-sans">
      <Navbar />
      <HeroSection />
      <div className="w-full max-w-5xl grid grid-cols-1 md:grid-cols-2 gap-8">
        <UploadSection />
        <FeatureSection />
      </div>
      <OutputSection />
      <AINotesGenerator />
      <MindAnalyzer />
      <DashboardInsights />
      <UserProfile />
      <Pricing />
      <Footer />
    </div>
  );
}